### PR TITLE
Refactor pdfjs components and content resizing

### PR DESCRIPTION
**Pull request by letavocado**
Due to the fact that I do not have access to private dataloop npm packages. I temporarily changed methods to access to dataloop resources.

App.original.vue  // backup of original App (with dataloop components)
App.vue // mocked entry point

App.vue and loading-task.js have a hard-coded auth `TOKEN` for accessing dataloop resources, as well as for httpsHeaders when requesting a pdf file from dataloop.

`TOKEN` expires after some time (about a day)
if you need another temporary token, you can contact me

### CODE REVIEW

**Comment by advaa1234** [comment]
Hey @flaxflour, unfortunately we cannot merge this PR as it contains a token that is hardcoded. This is bad practice to have on a source-tree even though it is expired.

If in the future you do encounter the need to do this, you can either handle it by adding it via .env and not have it committed, or work with it and not commit the token.

Closing this PR due to this issue.
Please open a new one without a token, and please clean up any comments in the codebase.

**Comment by letavocado** [comment]
Hi, @advaa1234. Thanks for the response. Yes, I know all this very well. But I have a good reason, why I did it this way, and not otherwise. Because I don't have access to private npm components. Such as : "@dataloop/components": "^0.6.6",
     "@dataloop/icons": "^1.0.74". I simulated the request to datalop items and commented out the part of the code that belongs to the "dl" library. And I backed up the original version, where requests to the dataloop are made using "dl" in the file App.original.vue. And the current version of App.vue is a temporary version, in order to make it convenient for you to test/review. I sent my own dataloop token which expires within a day and it is completely safe. I didn't move the token into the .env space as it's not appropriate in this context.  Since, the token cannot be hard-coded in .env, because it is more complex work and it has session timeout. To work with tokens, backend services are used to create new tokens, and the token have to periodically updated. After reviewing, it's just needed to delete the App.vue file and rename App.original.vue to App.vue. Hard-coded tokens and App.vue are mocks. Thanks for understanding. Let's discuss in more detail.

**Comment by fadiDL** [comment]
Hi @letavocado , we understand the issue and will be reopening this pull request and handling it accordingly.
For future reference please try to avoid committing the token even if its just for the pull request.
Thank you !

**Comment by advaa1234** [comment]
Merging into a side branch for testing

**Pull request merged**
