### PR TITLE
Update pdfjs

### PR DESCRIPTION
**Pull request by letavocado**
## Summary
~~Switching to a prebuild pdfjs~~
##### :fire:  Hotkeys are enabled. Which means:
  - <kbd>Ctrl</kbd> <kbd>F</kbd> or <kbd>⌘ (or Cmd)</kbd> <kbd>F</kbd> - toggle searchbar. <kbd>Esc</kbd> to close
  - <kbd>Enter</kbd> - to next search
  - <kbd>Shift</kbd> <kbd>Enter</kbd> - to previous search
            
##### :rocket: Performance enhancement 
  - ##### :eyeglasses:  Render only visible pages and thumbnails 
## Issue
Needed to add search functionality to the pdf component

## Changes
- ~~Custom PDF components replaced with [Prebuilt (modern browsers) PDF.js (Stable v3.6.172)](https://github.com/mozilla/pdf.js/releases/download/v3.6.172/pdfjs-3.6.172-dist.zip)~~
   - ~~[Prebuilt (modern browsers) PDF.js (Stable v3.6.172)](https://github.com/mozilla/pdf.js/releases/download/v3.6.172/pdfjs-3.6.172-dist.zip) contains all pdf features (including search functionality)~~
   - ~~pdfjs-dist removed from packages.json dependencies~~
- Other changes:
  - added linters and formatters(eslint, prettier, stylelint)
  - lint and format components and styles
  - refactor components to vue3(ts) composition api
  
## Screenshot
image

### CODE REVIEW

**Review by fadiDL — CHANGES_REQUESTED** [review]
@letavocado  why is pdfjs apart of our public files instead of it being an installed npm package as a dependency ?

Can you please try to either use a CDN or use the npm package instead of having the whole project stored in our public files ?

**Comment by letavocado** [comment]
Unfortunately, mozilla did not publish the release version in npm or in cdn.

**Comment by letavocado** [comment]
It can be placed in a separate repository and used as a submodule.

**Comment by letavocado** [comment]
Reason: Related issue is https://github.com/mozilla/pdf.js/issues/16126 and official [answer](https://github.com/mozilla/pdf.js/issues/16126#issuecomment-1458874547).

**Comment by fadiDL** [comment]
@letavocado You are correct that mozilla themselves do not publish their code as an npm package but they do base it off a CDN and there is a side project package called [`pdfjs-dist`](https://www.npmjs.com/package/pdfjs-dist) which was used in this project before

the package is up to date with the latest build of the mozilla project. 


As for your changes. in order to add search functionality you do not have to change all of our custom code of a viewer. in your answer it explicitly states that mozilla asks not use their viewer as is. instead they request you modify and reskin it

id prefer if you can use pdfjs-dist and generate a viewer like their code but in our own custom style instead. copying and using their code when they ask not to is not as nice.

**Comment by letavocado** [comment]
Thanks, @fadiDL! NP, just give me a time and it will be done with custom code.

**Comment by letavocado** [comment]
Hey @fadiDL! Check out and review this masterpiece 🫠

**Comment by letavocado** [comment]
Hey @fadiDL! Fixes already here and waiting for review.  🫨😀

Cheers!

**Review by fadiDL — APPROVED** [review]

**Pull request merged**
